---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-consumer-app
spec:
  replicas: 5
  selector:
    matchLabels:
      name: my-consumer-app
  template:
    metadata:
      labels:
        name: my-consumer-app
    spec:
      containers:
      - name: application
        image: your_docker_hub_account/my-consumer-app:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: dockerhub-secret
        ports:
          - containerPort: 3000
        env:
        # Define the environment variable
        - name: PROVIDER_URL 
          value: my-go-app-service
        - name: PROVIDER_PORT
          value: "3001"